# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
dist: trusty

warnings_are_errors: false
latex: false
env:
  global:
  - NOT_CRAN=true
os:
  - osx
  
branches:
  only:
    - master

r_packages:
  - rmarkdown
  - dplyr
  - tidyr
  - forcats
  - purrr
  - stringr
  - readr
  - lubridate
  - billboarder
  - knitr
  - kableExtra
  - leaflet
  - tidycensus
  - janitor
  - scales
  - DT
  - htmlwidgets
  - htmltools
  - sf
  - tibble
  - measurements

r_github_packages:
  - CT-Data-Haven/cwi
  
after_success:
  - Rscript -e "rmarkdown::render_site()"
  
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_PAT
  on:
    branch: master
  local_dir: docs
  keep_history: true
