# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages
dist: trusty
os:
  - osx

warnings_are_errors: false
latex: false
env:
  global:
  - NOT_CRAN=true
  
branches:
  only:
    - master

r_packages:
  - rmarkdown

script:
  - Rscript ./scripts/latest_data.R
  - Rscript -e "rmarkdown::render_site()"
  
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_PAT
  on:
    branch: master
  local_dir: dist
  keep_history: true

notifications:
  slack:
    secure: i2Ol1c7DZtf2kEpYBNLDIjYdPW7LKCcnJJV90WrlFwOTWrnfGqykqtvEunB1ia52cSP4J10AAH0CUVnjbaC5xLDbnTv3nNLYDlXVLDlNHpRWOjso0wivPICM/pBWkUaz3LA1VxXOYtn0OcoLy5GGJIMeZieOJqOL0lNBFaAnTMHpeRwsUfJGAfrf7KYhz8SsU0ORX0qGVTz2BFHrKG0+V2QGnQiD2jM8xjIaHul2uARaFg3+BZMclfED0/XJ5kMSCc2AlBSVOcqVvygZHRwSOVcK50RfpdIBK2/j8ofpfNl0sDNAJ8qqQbfoXDO9pwAnz9s3edfJ6OxZGjcAR9ExIjXOdl7lvfVxnZFP/Bkls+OgHdcHpu/2ybAvDYTlIRmsE68LmJbJik7mJh6MunWIM7T63A5eCFcFuoQqQpIp59rZ5EPjSD1cswAhu3nT4PN2tsYGThhzzFck7lc0Vm302nft6U+1MJ0IsdQnzNH7h09NGa9H/n2x2ecm+S7uyzAfl6EOyJRMmQXeVTydzn19zIuqpWCX2HELLaJB4I6WDseLLrcwnd8+B0rmpU8ciIS49czPnPt4+q+ZcsKjE+4kdDhpHC5czXplk7ftfQBLRcZApWxsYCuyGgp4qhhl6xiTGQ4Nry58uHwILaMDWu5OyCqCwGo6s9poMqd19nc8dh8=