language: r
sudo: false
cache: packages
dist: trusty
os:
- osx
warnings_are_errors: false
latex: false
env:
  global:
  - NOT_CRAN=true
branches:
  only:
  - master
r_packages:
- rmarkdown
- units
addons:
  homebrew:
    packages:
    - udunits
script:
- Rscript ./scripts/latest_data.R
- Rscript -e "rmarkdown::render_site()"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_PAT"
  on:
    branch: master
  local_dir: dist
  keep_history: true
notifications:
  slack:
    secure: NID0LSdLoirSysBWPF1FzSGGfbxRAtnKJgxfcKqMNiHELqLnVXKm1qPYfvsIo0VtXqcvzGYi+CrIwKifUuDRAOd3hZm8KRuQWyPceGkOUEhl8OB48iqovsyvlrLxVLcFkDQci8Y2IQHDraXeYpVNEsoo+GtJ9H8UvOWRoGAU0GIw9d3LJAI6KwkV/9ltM+h+2wKAW5Eb1pKqgcU5YsNLzI/S0WuYDpF/BPB2gdZpYL/xtNX/HxmSyvougpAiLxHrq+4rrU7ZO2TPDoeMCc5GfdTgZXE8ZDO3UNS2v4W+Uj1AupM2wlK1A5SQgf9Z+btdBexR1neC9If86XMfCRyiGVRznsid8bCZ08wGvjn+teG6YqgcYFDCqvm46PTBB7TrGEwxbPgP1mRZJjA2l93I0KlQ0K4fpeKn271QZX8l24H0xWBnw+L5AOFTIku5N7MSf6fIOUfqa+2Fuw2FgQWzdBXteJ9+V6sl9iFA01t4C6c2jaAf29aWozDcEOmSWg/+21AoxZRRJ9mHwt94vglasZeRgFF6OrbM81h/qGOG2bx4fYPbEyC4GFA1SOp8rdxlqvUET/3thmhd2Lgt/EMSpQsU2eklj+nS9udAydbC3dfQducPlFUozpBFy5oA4WpHIVvIDEVdh4p+T1HLPlaQMIwP2oFqDmK3TpBwlSuzMpo=
