language: r
sudo: true
cache: packages
dist: trusty
warnings_are_errors: false
latex: false

env:
  global:
    - NOT_CRAN=true
os:
  - osx
  
branches:
  only:
    - master
    
r_packages:
  - rmarkdown
r_github_packages:
  - CT-Data-Haven/cwi
  
after_success:
  - rm -rf dist
  - Rscript -e "rmarkdown::render_site()"
  
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_PAT
  on:
    branch: master
  local_dir: dist
  keep_history: true
