language: r
sudo: false
cache: packages
dist: trusty
os:
- osx
warnings_are_errors: false
latex: false
env:
  global:
  - NOT_CRAN=true
branches:
  only:
  - master
r_packages:
- rmarkdown
- units
addons:
  homebrew:
    packages:
    - udunits
script:
- Rscript ./scripts/latest_data.R
- Rscript -e "rmarkdown::render_site()"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_PAT"
  on:
    branch: master
  local_dir: dist
  keep_history: true
notifications:
  slack:
