---
title: "COVID-19 in Connecticut"
output:
  html_document:
    toc: true
    toc_depth: 2
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
# library(covidpub)
options(lubridate.week.start = 1)
```

```{r meta}
main_dates <- fetch_main_date_range()
counties <- sort(unique(town_county$county))
pals <- make_colors()
county_pal <- setNames(pals$qual_pal, c("Connecticut", counties)) %>%
  rlang::set_names(stringr::str_remove, " County$")
race_pal <- setNames(pals$qual_pal[c(1, 8, 5, 6, 7)], c("Total", "Black", "Latino", "White", "Asian"))
cat_pal <- setNames(pals$qual_pal[c(1, 3, 6, 5, 8)], c("CT", "By age", "By income", "By race/ethnicity", "By presence of kids"))
```


```{r single-day-cases-table}
make_1d_cases_table(max(main_dates))
```

```{r cases-by-race-bars}
age_adj_charts <- make_age_adj_race_charts(race_pal)
age_adj_charts[["Cases per 10k"]]
```

```{r deaths-by-race-bars}
age_adj_charts[["Deaths per 10k"]]
```

```{r cases-by-county-bars}
make_county_trend_chart(county_pal)
```

```{r state-metrics-lines}
make_metrics_trend_chart(pals$qual_pal[c(5, 7, 6, 8)])
```

```{r test-pos-lines}
make_test_pos_chart(pals$qual_pal[2])
```

```{r hosp-change-bars}
make_hosp_change_chart(rev(pals$div_pal3))
```

```{r wk-to-wk-change-table}
make_period_change_table()
```

```{r wkly-new-cases-bars}
make_period_change_bars(pals$div_pal5)
```

```{r cws-trust-bars}
make_cws_trust_bars(pals$qual_pal[1])
```

```{r cws-leave-home-bars}
make_cws_leave_home_bars(cat_pal)
```

```{r hhp-lost-work-bars}
hhp_bars <- make_hhp_single_bars(cat_pal)
hhp_bars[["lost_work"]]
```

```{r hhp-food-bars}
hhp_bars[["food_insecure"]]
```

```{r hhp-housing-bars}
make_hhp_housing_bars(pals$qual_pal[c(1, 3)])
```


