name: site-build
on:
  push:
    branches:
      - main
      - master

jobs:
  build-site:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CRAN: "https://packagemanager.rstudio.com/all/__linux__/focal/latest"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install ubuntu dependencies
        run: |
          sudo apt-get install -y \
            libcurl4-openssl-dev \
            libudunits2-dev

      - name: Install pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Install project packages
        uses: r-lib/actions/setup-renv@v2

      - name: Install package
        run: |
          install.packages("devtools")
          devtools::install(pkg = ".", build = TRUE, upgrade = FALSE)
        shell: Rscript {0}

      - name: Render site
        run: Rscript -e 'rmarkdown::render_site(input = "site")'

      - name: Get latest date
        run: |
          # get latest statewide date
          echo "LATEST_DATE=$(tail -n 1 input_data/covid_county.csv | cut -f 2 -d ,)" >> GITHUB_ENV

      - name: Make update badge
        uses: schneegans/dynamic-badges-action@v1.3.0
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gistID: 418c1b0228bd7ac4f5b835fd54249a73
          filename: latest_covid_data.json
          label: Latest data
          message: ${{ env.LATEST_DATE }}
          color: pink
          style: flat-square

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.2.0
        with:
          branch: gh-pages
          folder: dist
