name: Render and Deploy RMarkdown Website
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      
      - name: Install pandoc
        uses: r-lib/actions/setup-pandoc@v1
      
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "renv", "rmarkdown"))
        shell: Rscript {0}
        
      - name: Install project packages
        run: |
          renv::restore()
        shell: Rscript {0}
      
      - name: Render site
        run: |
          rmarkdown::render_site()
        shell: Rscript {0}

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        env:
          BUILD_DIR: dist
          GH_PAT: ${{ secrets.GH_PAT }}
