name: update-data-pr
on:
  push:
    branches:
      - update
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - name: Create PR
      #   uses: peter-evans/create-pull-request@v4
      #   with:
      #     branch: update-working
      #     base: main
      - name: Create PR
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "main"
          github_token: ${{ secrets.PR_PAT }}
