name: update-data-pr
on:
  push:
    branches:
      - update
  workflow_dispatch:

jobs:
  file-pr:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Copy updated data
        id: copy_data
        run: |
          # make a temp branch from main, checkout input_data from update, file pr
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git pull 
          git branch --list
          git branch --force tmp origin/main
          git checkout tmp
          git checkout update -- input_data

          # list updated input data
          CHANGED_CSV=( $(git diff --name-only | grep -E \.csv --include=input_data) )
          echo "PR_LIST=$(for f in $CHANGED_CSV; do echo '* $f'; done" >> GITHUB_ENV

          # get latest statewide date
          echo "LATEST_DATE=$(tail -n 1 input_data/covid_county.csv | cut -f 2 -d ,)" >> GITHUB_ENV

          if [ -n "$(git status --porcelain)" ]; then
            echo "::set-output name=make_pr::true"
            git commit -m "Update data to $LATEST_DATE"
            git push origin tmp
          else
            echo "::set-output name=make_pr::true"
            echo "No changes"
          fi
          exit 0

      - name: Make update badge
        uses: schneegans/dynamic-badges-action@v1.3.0
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gistID: 418c1b0228bd7ac4f5b835fd54249a73
          filename: latest_covid_data.json
          label: Latest data
          message: ${{ env.LATEST_DATE }}
          color: "#f3b5e9"
          style: flat-square

      - name: Create PR
        uses: repo-sync/pull-request@v2
        if: ${{ steps.copy_data.outputs.make_pr }}
        with:
          source_branch: "tmp"
          destination_branch: "main"
          github_token: ${{ secrets.PR_PAT }}
          pr_title: "Pull data as of ${{ env.LATEST_DATE }}"
          pr_body: "# Updates:\n\n${{ env.PR_LIST }}"
          pr_label: "update-data,auto-pr"
