name: update-data-pr
on:
  push:
    branches:
      - update

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create PR
        uses: peter-evans/create-pull-request@v4
        with:
          branch: update
          base: main
